---
title: "Hướng dẫn viết bài luận du học bậc cao học (SOP)"
author: "내 사랑 유나"
date: today
crossref:
  sec-prefix: Mục
format: 
  html:
    toc: true
    toc-depth: 2
    number-sections: true
    embed-resources: true
    css: styles.css
---

**Lưu ý**: 

- Bài này chỉ nói đến dạng bài luận phổ biến nhất khi nộp hồ sơ ở bậc cao học là Statement of Purpose (SOP). Một số trường đại học (đặc biệt là ở Mỹ) có thể yêu cầu nhiều dạng bài luận hơn, chi tiết hơn có thể xem ở [đây](https://www.cmu.edu/student-success/other-resources/handouts/comm-supp-pdfs/types-of-application-essays-for-graduate-school.pdf).
- SOP có thể có nhiều tên gọi khác nhau như Motivation Letter (thường dùng ở châu Âu) hay Personal Statement (trùng tên với một dạng khác). Vì vậy, cần đọc yêu cầu của trường để xem thực sự bài luận mình cần viết ở dạng nào.
- Các nội dung trong bài này nên được áp dụng một cách linh hoạt vì không có cách viết SOP nào đúng hoặc sai.

# Mindset khi viết SOP
Trước tiên, chúng ta cần hiểu mục đích của bài SOP (phục vụ cho quá trình **tuyển sinh** --- về bài luận học bổng chúng ta sẽ bàn ngay sau đây) là **chứng minh mình là một ứng viên mạnh và phù hợp với chương trình**. Sự phù hợp này có thể được thể hiện ở hai khía cạnh:

- **Tại sao họ nên chọn mình?** (vì mình sẽ thành công khi theo chương trình của họ)
  - Background của mình phù hợp với chương trình.
  - Mục tiêu nghề nghiệp của mình phù hợp với cái chương trình hướng đến.
  - Mình là một ứng viên mạnh vì có nhiều thành tích trong học tập và công việc.
  - Mình sẽ đóng góp cho chương trình và cộng đồng cựu sinh viên.
  - ...
- **Tại sao mình lại chọn họ?** (trong vô vàn chương trình, tại sao mình lại chọn họ?)
  - Chương trình bổ sung những kiến thức, kỹ năng mình cần để theo đuổi con đường sự nghiệp mình mong muốn.
  - Chương trình có những giáo sư có thể giúp mình theo đuổi hướng nghiên cứu yêu thích.
  - Chương trình có mạng lưới cựu sinh viên năng động trong hướng mình theo đuổi.
  - ...

Vì vậy, điều đầu tiên chúng ta cần nghĩ đến khi viết SOP chính là **sự phù hợp**. Để tìm ra sự phù hợp của mình với chương trình, ta cần thử suy nghĩ về background và mục tiêu của mình, sau đó so khớp với những thứ chương trình yêu cầu và hướng đến. Chúng ta cùng xét ví dụ sau: bạn Hưng tốt nghiệp chuyên ngành Toán học và đang làm chuyên viên phân tích tài chính ở một ngân hàng. Mong muốn của bạn Hưng là trở thành quản lý danh mục đầu tư (portfolio manager) tập trung vào các phương pháp định lượng. Do đó, bạn đang nộp hồ sơ vào chương trình Thạc sĩ Toán Tài chính của trường University College London. Dưới đây là bảng so khớp bạn Hưng và chương trình:

|Khía cạnh|Bạn Hưng| Chương trình Thạc sĩ Toán Tài chính|
|-------------------------|-------------------------|-------------------------|
|Background|Nền tảng toán học + kinh nghiệm làm việc|Chương trình học yêu cầu đầu vào nặng toán|
|Mục tiêu nghề nghiệp |Trở thành quản lý danh mục đầu tư (portfolio manager) tập trung vào các phương pháp định lượng| Bạn Hưng đã có nền tảng về toán học nhưng thiếu kiến thức về các phương pháp định lượng trong tài chính → chương trình cung cấp các môn học để bổ sung kiến thức này|

Hồ sơ của bạn Hưng có lẽ là đẹp trong mơ rồi. Bây giờ chúng ta hãy cùng xem xét một ví dụ khó hơn (và cũng chỉ có trong tưởng tượng): chị Tzuyu là thành viên một nhóm nhạc nữ thần tượng Hàn Quốc nổi tiếng. Tuy nhiên, chị lại có bằng thạc sĩ [Tâm lý học ứng dụng](https://www.ceiba-bs.com/master-in-psychology/) của trường [Miguel de Cervantes European University](https://en.m.wikipedia.org/wiki/Miguel_de_Cervantes_European_University) mà không có bằng đại học. Chúng ta hãy cùng tưởng tượng chị ấy đã trải qua quá trình nộp hồ sơ thế nào (nhấn mạnh một lần nữa đây là tưởng tượng). Vì không có bằng đại học, tuy nhiên chị ấy có thể background làm việc gần 10 năm, từng tiếp xúc với nhiều người, đi nhiều nơi. Trong mục *Admission requirements* của chương trình có ghi *Special cases can be accepted on individual basis after decision of the admission committee*. Quan trọng hơn cả là background của chị ấy tương đối đặc biệt và sẽ làm tăng thêm sự đa dạng (và danh tiếng) cho chương trình. Về mục tiêu nghề nghiệp, có thể chị ấy muốn trở thành giám đốc sáng tạo sau khi "giải nghệ", do đó, việc có kiến thức về tâm lý học sẽ giúp chị ấy hiểu hơn về các nghệ sĩ cũng như khán giả, qua đó xây dựng các concept phù hợp.

::: {.callout-tip title="Tóm lại là ..."}
Dài dòng vậy thôi, chứ tóm lại là có 2 điểm **quan trọng** sau cần lưu ý (các điểm khác có thể du di được):

- Background có phù hợp với chương trình không? (mục đích chính là chứng minh mình đủ năng lực/mình là ứng viên mạnh theo học/làm nghiên cứu chương trình) Nếu học đại học ngành liên quan thì khá dễ. Nếu không thì phải có gì đó thay vào.
- Mục đích. Tại sao mình lại cần học chương trình này? Khi học xong mình sẽ làm gì? Chương trình sẽ giúp mình có được công việc đó thế nào? Cái này thì thật ra có thể bịa nhưng tóm lại là phải có.
:::

::: {.callout-note title="Thế còn bài luận xin học bổng thì sao?"}
Về cơ bản, bài luận xin học bổng cũng có thể coi là bài SOP (trừ khi học bổng đó đưa ra đề bài cụ thể cho bài luận). Tuy nhiên, chúng ta cần dựa vào các tiêu chí và mục đích của học bổng để thể hiện 2 điều trên một cách rõ ràng hơn. Hay nói cách khác, chúng ta cần xem họ đang tìm kiếm điều gì và phải làm nổi bật được những điểm tương ứng trong bài luận (và cả hồ sơ) của mình. Ví dụ, đối với học bổng chính phủ, ở phần "tại sao mình lại chọn họ?", chúng ta nên đưa ra lý do tại sao mình lại chọn đất nước đó, sau khi học xong mình có thể góp phần phát triển đất nước của mình thế nào. Hay đối với các học bổng need-based, chúng ta có thể về việc mình khó khăn thế nào. Tương tự đối với các học bổng merit-based, chúng ta cần làm nổi bật phần thành tích học tập của mình. **Tựu trung lại**, do học bổng có thể coi là một khoản "đầu tư" của họ cho mình, chúng ta cần thuyết phục được mình sẽ thành công (hay nói cách khác là "sinh lời") khi nhận học bổng, vì vậy họ nên chọn mình. Còn thế nào là thành công thì tùy vào tiêu chí của học bổng đó.
:::

Một sai lầm phổ biến khi viết SOP là **chỉ tập trung vào liệt kê thành tích**, hoặc kể về trải nghiệm của mình mà **không có ngữ cảnh, không có sự liên kết với chương trình**. Chúng ta cần lưu ý rằng việc liệt kê thành tích đã được làm ở trong CV, vì vậy không cần làm vậy ở trong SOP nữa. Có thể kể ra một số thành tích nổi bật nhất, tuy nhiên phải đặt ở trong ngữ cảnh (ví dụ như viết về mục tiêu nghề nghiệp, hoặc những thành tích đó sẽ giúp mình học tập/đóng góp cho chương trình thế nào). Tương tự, việc kể về các trải nghiệm thường phải góp phần trả lời một trong hai câu hỏi về sự phù hợp bên trên. Có thể trải nghiệm đó đã giúp mình thể hiện được các phẩm chất, kỹ năng mà chương trình đang tìm kiếm, chuẩn bị tốt hơn cho chương trình, hoặc thúc đẩy mình nộp hồ sơ. Điều này sẽ được trình bày rõ hơn qua các ví dụ thực tế ở phần sau.

::: {.callout-tip title="SOP không phải là bài khoe thành tích"}
Một ngộ nhận phổ biến có lẽ là kể ra nhiều thành tích = mình giỏi = họ sẽ nhận mình? Thực ra điều này không sai nhưng cũng hoàn toàn đúng. Quan trọng vẫn là sự phù hợp với chương trình. Đó cũng là lý do các bài luận nộp cho các chương trình khác nhau cũng nên khác nhau.
:::

Ngoài ra, cần lưu ý rằng mỗi ngành học có thể có kỳ vọng khác nhau về bài luận. Ví dụ, ngành công tác xã hội có thể cần bài luận hướng về các câu chuyện cá nhân hơn, trong khi các ngành khoa học--kỹ thuật thì bài luận thường thuần về chuyên môn, các ngành thiên về ứng dụng có thể cần bài luận tập trung vào các trải nghiệm đi làm, ... Vì vậy, người viết cần tìm hiểu và sử dụng lối viết phù hợp cho bài luận cho ngành học của mình.

Cuối cùng, khi viết chúng ta cần nghĩ đến những người đọc, chính là hội đồng tuyển sinh của chương trình. Họ phải đọc hàng trăm bài luận khác nhau, vì vậy không thể dành quá nhiều thời gian cho một bài. Do đó, chúng ta cần viết ngắn gọn, xúc tích, vào thẳng trọng tâm vấn đề, không quá dài; tách đoạn hợp lý, mỗi đoạn có câu chủ đề để dễ theo dõi. Hay nói cách khác, chúng ta phải viết sao cho họ đọc lướt qua cũng có thể hiểu được ý chính. Ngoài phần câu từ, mặt hình thức cũng tương đối quan trọng. Người viết cần định dạng văn bản với font chữ, cỡ chữ, dãn dòng, căn lề, ... sao cho dễ nhìn nhất có thể.

# Những nội dung có thể viết trong SOP
Phần này cũng là những câu hỏi để người viết suy nghĩ trước khi bắt đầu viết. Lưu ý, đây không phải là dàn ý cho SOP, chỉ là các nội dung/chủ đề người viết cần trình bày trong SOP. Phần dàn ý sẽ được trình bày ở @sec-sop-structure.

## Những nội dung rất nên có
### Động lực
::: {.callout-note title="Tóm lại là ..."}
Kể ra một câu chuyện dẫn đến việc mình quyết định nộp hồ sơ vào chương trình. Thường thì câu chuyện sẽ liên quan đến mục tiêu của mình và việc theo học chương trình (và rộng hơn là ngành, vì vậy có thể nói về câu chuyện dẫn đến quyết định chọn ngành trước) sẽ giúp mình đạt được mục tiêu.
:::

Câu chuyện này thường được phát triển theo các khía cạnh sau đây (có thể nhiều hơn một khía cạnh)

Hoàn cảnh cá nhân
: Thường thì đây sẽ là một câu chuyện mang tính cá nhân theo mô-típ: người viết ở trong một hoàn cảnh (khó khăn) nào đó/gặp một tình huống (chấn động) làm thay đổi cuộc đời, từ đó nhận ra tầm quan trọng của cái ABC và quyết định theo cái đó. Sau đó, người viết sẽ kể về hành trình theo đuổi cái ABC ở đại học.

*Ví dụ 1* ([nguồn](https://www.uc.edu/news/articles/2024/11/personal-statement-examples-grad-school.html))

<div class="example">
  My passion for public health was sparked during a volunteer trip to [country], where I worked alongside local health officials to improve sanitation and nutrition in rural communities. Witnessing firsthand the challenges that underserved populations face in accessing basic healthcare motivated me to pursue a career in public health. With a background in biology and a deep commitment to improving health equity, [I am eager to advance my education in public health at [university] and contribute to global efforts in disease prevention, health education and health policy reform.]{.h-yellow}
</div>

*Ví dụ 2* ([nguồn](https://www.collegeessayguy.com/blog/statement-of-purpose-examples))
<div class="example">
  One of the most prominent instances that made me realize the deep-seated educational disparities for minority and lower-income students occurred when I tested a 5th grade Philadelphia public school student named Jenna. Her results revealed that Jenna was barely capable of reading on a 1st grade level. Despite the fact that my interaction with Jenna left me upset and frustrated, it catalyzed my desire to work towards narrowing the achievement and opportunity gaps that students and school systems encounter in our country. 
 
  [Pursuing a Master’s degree in Sociology and Education at Teachers College will empower me to better support underserved students by gaining a comprehensive understanding of the U.S. education system, engaging with professors who are leaders in the field of urban education, and acquiring research skills that will enable me to critically analyze school systems from a sociological perspective.]{.h-yellow}
</div>

Hướng nghiên cứu
: Đây là một câu chuyện thường dùng nếu người viết theo học các chương trình cao học định hướng nghiên cứu. Mô-típ thường thấy là ở đại học theo đuổi hướng ABC, bây giờ muốn phát triển thêm, hoặc phát triển hướng XYZ liên quan.

*Ví dụ* ([nguồn](https://mitcommlab.mit.edu/meche/wp-content/uploads/sites/8/2021/11/Annotated-Personal-statement-1.pdf))

<div class="example">
  From my previous research experiences I have learned that working on a research project has been the best motivation and also the best learning platform for me. During my undergraduate years at MIT, I have had the opportunity to work in the XXXX Laboratory and intern at the XXXX Center. [These opportunities inspired me to apply to XXXX graduate program in Mechanical Engineering in order to pursue a PhD with a focus on robotics, combined with bio-inspired design.]{.h-yellow}
</div>

Nhu cầu
: Đây thường là một câu chuyện mang tính thuần chuyên môn theo mô-típ: người viết làm nghiên cứu/đi làm gặp một "vấn đề" trong công việc, do đó cần học thêm cái ABC để có thể phát triển thêm. Hoặc mục tiêu nghề nghiệp là cái XYZ nên cần học cái ABC để đạt được do nền tảng kiến thức chưa đủ, dẫn đến nộp hồ sơ vào chương trình này.

*Vi dụ* ([nguồn](https://writeivy.com/ms-finance-sop/))

<div class="example">
  During the summer of 2022, I worked as a front-end development intern at FinLight, Canada’s largest financial data service. There, my responsibilities included building the user interface for their financial terminal. However, I soon found myself most fascinated by Light API, a backend data service that enables quantitative-model construction and strategy backtesting for client researchers. This high-performing, real-time software was so impressive that, when I returned to Metropolis University, I quickly enrolled in Mathematics and Finance coursework alongside my Computer Science major. My goal was to acquire the theoretical knowledge necessary to build tools and frameworks for financial-data analytics myself. Since then, I have completed courses in ML, NLP, and Predictive Analytics, in conjunction with extensive coursework in Statistics, Probability Theory, and Financial Mathematics, and furthered my understanding of these subjects through independent research and real-world projects.

  Today, I hope to expand upon these experiences by studying and conducting research at the intersection of finance and machine learning, with a focus on generative adversarial networks and ML models to synthesize alternative financial data. [Specifically, I hope to understand how the ML models traditionally used for institutional high-frequency trading (e.g. Markov Decision Models within Reinforcement Learning) can be adopted into accessible personal-finance tools for retail investors. The Master of Science in Computational Finance at Gotham will make that possible.]{.h-yellow}
</div>

Việc viết theo hướng nào sẽ phụ thuộc vào ngành và những trải nghiệm, câu chuyện cá nhân của người viết. Mục tiêu là đưa ra một câu chuyện hợp lý để giải thích cho động lực nộp hồ sơ vào chương trình của người viết.

### Trải nghiệm và câu chuyện cá nhân
::: {.callout-warning title="Nhưng phần trước cũng là kể chuyện mà ..."}
Thì đúng rồi, phần này có thể có sự chồng chéo với phần trước. Có thể kể một câu chuyện vừa đưa ra động lực vừa phục vụ các mục đích khác. Cái khác là phạm vi (scope) của phần này rộng hơn.
:::

::: {.callout-note title="Tóm lại là ..."}
Kể về các trải nghiệm và câu chuyện liên quan nhằm thể hiện một hay nhiều mục đích sau:

- Cho thấy sự chuẩn bị của mình cho chương trình.
- Cho thấy mình là ứng viên mạnh.
- Cho thấy mình sẽ là một sinh viên cao học thành công.
- Cho thấy mình có những phẩm chất/năng lực mà chương trình đang tìm kiếm.

Khi kể về các trải nghiệm, ta nên theo kèm *ý nghĩa* (trả lời cho câu hỏi *why does it matter?*). Hay nói cách khác, cần chỉ ra (một hay nhiều):

- Qua trải nghiệm đó học được gì? Có giúp gì cho mình khi theo học cao học không?
- Trải nghiệm đó thể hiện phẩm chất/năng lực gì mà chương trình tìm kiếm?
- Trải nghiệm đó có liên kết gì với định hướng trong tương lai của mình?

Còn nếu là câu chuyện cá nhân, cần kể ngắn gọn, cô đọng, cho thấy sự phát triển của bản thân mình. Câu chuyện này cần có sự liên kết với các trải nghiệm khác (thường nằm một chuỗi các sự việc dẫn đến ngày hôm nay).
:::
Các loại trải nghiệm có thể kể đến bao gồm:

Trải nghiệm học tập
: 
- *What*: Cần thiết nếu người viết nộp hồ sơ vào một chương trình trái ngành hoặc chương trình yêu cầu cao về mặt kiến thức. Có thể kể ra mình đã học các môn nào liên quan đến chương trình cao học, kèm theo điểm số (nếu điểm cao), bài tập nhóm, ...
- *Why it matters*: Chứng minh mình đã chuẩn bị tốt về mặt kiến thức để theo học cao học.

*Ví dụ* ([nguồn](https://writeivy.com/how-to-write-the-human-computer-interaction-sop-sample-guide/))

<div class="example">
  Studying architecture at Metropolis University proved valuable in learning problem-solving through design-thinking. **[1]** I studied how physical space can shape opportunities for user interactions, and through intensive studios, learned to design at different scales. In one particular course of note, Design Operations and Tactics with Professor Barbara Gordon, **[2]** I explored how embedded technologies provide a framework for improvisation between people and the urban environment. Utilizing architecture as a technological interface, and analyzing concepts such as ubiquitous computing and calm technology, [I obtained my first introduction to the world of HCI.]{.h-green} 
</div>

::: {.column-margin}
<div class="h-green-box">
  **Why it matters**: Ở đây ứng viên đang nộp hồ sơ thạc sĩ ngành HCI. Các trải nghiệm về việc học được kể ra trước đó [1] [2] là những trải nghiệm đầu tiên trong ngành HCI.
</div>
:::

Trải nghiệm nghiên cứu
: 
- *What*: Loại này thường được dùng trong các chương trình định hướng nghiên cứu như tiến sĩ hoặc thạc sĩ trong khối STEM. Người viết có thể kể về kinh nghiệm tham gia nghiên cứu khoa học ví dụ như làm lab/riêng với giảng viên, làm trong khuôn khổ các cuộc thi, hay thậm chí là khóa luận tốt nghiệp có yếu tố nghiên cứu. Lưu ý cần trình bày về **vấn đề nghiên cứu, mình có đóng góp gì/vượt qua khó khăn thế nào, qua đó mình học được gì, kết quả ra sao (nếu có cụ thể về số liệu hay đăng ở tạp chí/hội thảo nào đó thì tốt), có ảnh hưởng thế nào đến định hướng/con người mình.**
- *Why it matters*: Chứng minh năng lực nghiên cứu của mình (cần thiết cho các chương trình định hướng nghiên cứu).

*Ví dụ* ([nguồn](https://iastate.pressbooks.pub/statementofpurpose/chapter/research-experience/))

<div class="example">
  My participation with Dr. Wade’s lab [inspired my current independent research project further exploring resilience factors in the Black community]{.h-green}. Specifically, this project [examines the intersectionality of religion and the Black experience]{.h-blue} revolving around discrimination and racial identity. As this project is ongoing, I am in the process of [examining the role of religious commitment and racial identity]{.h-red} as protective measures against the psychological distress that often results from the discrimination and racism that Black individuals endure. [This project is important in my transition from undergrad to graduate school because it provides an opportunity for me to conduct my own research based on my specific research interests.]{.h-green}
</div>

::: {.column-margin}
<div class="h-green-box">
  **Why it matters**: Ở đây ứng viên nêu lên vai trò của nghiên cứu đối với định hướng của bản thân.
</div>

<div class="h-blue-box">
  Vấn đề nghiên cứu.
</div>

<div class="h-red-box">
  Ứng viên đã làm gì.
</div>
:::

Trải nghiệm làm việc
: Tương tự như trải nghiệm nghiên cứu. Cũng là nói về mình đã làm gì, học được gì, kết quả ra sao, ảnh hưởng đến mình thế nào ...

*Ví dụ 1* ([nguồn](https://writeivy.com/ms-finance-sop/))

<div class="example">
  Outside school, multiple software-development internships have [inspired me to learn more about financial technologies]{.h-green}. [**[1]**]{.h-red} At FinLight in 2022, I implemented the UI for Light Terminal’s macroeconomics indicators dashboard, [witnessing the solutions the terminal provides—from real-time quotes for quantitative trading to risk management and macro research.]{.h-grape} [**[2]**]{.h-red} At ByBit in the summer of 2023, I worked on an integration project for the Institutional Reports service, incorporating new features like real-time streaming updates and flexible time-range inputs. I was also responsible for a series of investigations into transaction discrepancies that [were particularly fruitful]{.h-grape}. By delving into upstream and downstream services to locate errored logic, and by collaborating with trading teams to resolve numeric precision issues, [I learned much about the adaptation of GRPC microservices within this distributed cryptocurrency exchange system]{.h-green}—[an understanding that will greatly aid my efforts at Gotham and beyond.]{.h-green}
</div>

::: {.column-margin}
<div class="h-green-box">
  **Why it matters**: Ứng viên đã học được gì và điều đó giúp cho việc học cao học thế nào.
</div>

<div class="h-grape-box">
  Kết quả của việc ứng viên đã làm (phần fruitful có thể viết cụ thể hơn).
</div>

<div class="h-red-box">
  **[1], [2]**: Ứng viên đã làm gì.
</div>
:::

*Ví dụ 2* ([nguồn](https://www.uc.edu/news/articles/2024/11/personal-statement-examples-grad-school.html))

Đây thực ra trông giống một dạng "template" hơn và chúng ta có thể thấy nó có đầy đủ các yếu tố cần trình bày.

<div class="example">
  Over the past [X] years, I have gained hands-on experience at [company], where I have contributed to [[key projects, achievements or responsibilities]]{.h-red}. In my role as [your current position], I have developed expertise in [relevant skills: project management, financial analysis, data-driven decision-making] and have worked with cross-functional teams to [describe key outcomes or contributions]. For instance, I led a team that [specific accomplishment], resulting in [[impact: increased revenue, improved operational efficiency, cost savings]]{.h-grape}. [This experience has deepened my understanding of the complexities of business and sharpened my problem-solving abilities.]{.h-green}
</div>

::: {.column-margin}
<div class="h-red-box">
  Ứng viên đã làm gì.
</div>
<div class="h-grape-box">
  Kết quả của việc ứng viên đã làm.
</div>
<div class="h-green-box">
  Why it matters.
</div>
:::

Hoạt động ngoại khóa
: 
- *What*: Cần thiết cho một số ngành quan trọng về trải nghiệm xã hội. Cần nhấn mạnh vào việc hoạt động ngoại khóa đó ảnh hưởng đến mình thế nào, qua đó mình học được gì, có ý nghĩa thế nào với mình khi học cao học.
- *Why it matters*: Góp phần thể hiện một số phẩm chất chương trình có thể yêu cầu.

*Chưa tìm được ví dụ*

### Sự phù hợp với chương trình
::: {.callout-note title="Tóm lại là ..."}
Giải thích tại sao mình lại chọn chương trình này trong vô vàn chương trình khác. Một số lý do có thể kể đến:

- Các môn học phù hợp, giúp mình bổ sung kiến thức hoặc phát triển thêm sẵn có nền kiến thức của mình.
- Các cơ hội nghiên cứu với các giáo sư phù hợp với hướng nghiên cứu của bản thân.
- Các hoạt động khác như thực tập, hợp tác với doanh nghiệp, ...

Quan trọng nhất là cần giải thích các thứ trên giúp mình **đạt được mục tiêu** thế nào. Chứ nếu chỉ liệt kê ra thì không khác gì bê nguyên từ mô tả của chương trình.
:::

*Ví dụ 1* ([nguồn](https://caw.ceu.edu/some-samples-statements-purpose)):

<div class="example">
  I am aware of the high reputation of your school and the excellent Master's program that you offer at the Norman Paterson School of International Affairs. I believe it will certainly help me with my research and career objectives either [through work in diplomatic service or at an international organization]{.h-yellow} where I will be able to apply my knowledge and skills obtained through studies at your University.

  Courses such as Conflict Analysis, International Mediation and Conflict Resolution and International Organizations in International Affairs [will be very helpful for my analyzing of the problems in the South Asian subcontinent]{.h-green} and beyond it and will allow me to [deeper understand the reasons for numerous interstate and intrastate conflicts that persist in the region]{.h-green}. Moreover these courses will be of particular [relevance to my career plans]{.h-green} which are to find employment with UN or a similar institution in the field of conflict resolution and peacekeeping. The possibility to combine theoretical studies with practical skills in conflict analysis and resolution at the Carleton University will [enable me to become a good specialist who will be able to contribute to the common cause of peace in the world]{.h-green}. I am eager to become a professional orientalist, as I believe this field of study will always be important in the changing world where Asian countries such as India and China play significant roles in the international arena. MA at the Carleton University would be a precious experience both in terms of my academic and professional career. I hope you will give me the opportunity to realize my ambition.
</div>

::: {.column-margin}
<div class="h-yellow-box">
  Mục tiêu của ứng viên.
</div>

<div class="h-green-box">
  Các môn học trong chương trình sẽ giúp gì cho ứng viên **trong việc đạt được mục tiêu**.
</div>
:::

*Ví dụ 2* ([nguồn](https://owl.purdue.edu/owl/job_search_writing/preparing_an_application/writing_the_personal_statement/examples.html))

<div class="example">
  My second research interest is monitoring pathogens in human populations. Because of my curiosity, I was particularly impressed by a related research article by [Dr. Layne]{.h-yellow} entitled, “Human Influenza Surveillance: The Demand to Expand.” This article was published in the Emerging Infectious Diseases Journal in 2006. [In his article, Dr. Layne explained how a high throughput laboratory network can provide faster vaccine-delivery methods and monitor changes in the epidemic Influenza strains. I would look forward to working with Dr. Layne because it is an opportunity to expand my knowledge of medically relevant pathogens.]{.h-green} This type of research has the potential to improve the effectiveness of the existing Influenza protocol and to invest in the future health and well-being of the world’s population.
</div>

::: {.column-margin}
<div class="h-yellow-box">
  Đưa ra tên giáo sư cụ thể mình muốn làm cùng.
</div>

<div class="h-green-box">
  Giải thích hướng nghiên cứu của mình và giáo sư liên quan gì đến nhau.
</div>
:::

### Kế hoạch tương lai
::: {.callout-note title="Tóm lại là ..."}
Sau khi tốt nghiệp mình sẽ làm gì, có thể chia ra ngắn hạn và dài hạn? Nói chi tiết, cụ thể hơn về mục tiêu của mình và nhấn mạnh lại chương trình sẽ giúp mình đạt được mục tiêu đó.
:::

*Ví dụ 1* ([nguồn](https://writeivy.com/course-based-masters-sop/))

<div class="example">
  After graduation, my [short-term goal]{.h-yellow} is to contribute to projects that help close the gap in AI technology between rural and urban hospitals, hopefully in companies like Arterys and Enlitic, both of which design image-classification tools for medical diagnosis. [Long-term]{.h-yellow}, I hope to contribute towards creating an AI-powered medical-imaging platform that can integrate rural communities (like those of South Africa’s Eastern Cape Province) into our modern healthcare infrastructure, via collaborative non-profit work. I believe Gotham’s Master of Artificial Intelligence program will [provide me with the knowledge and experience I need to achieve these goals]{.h-green}, and work toward innovating the future of healthcare systems in developing nations who could most benefit from these efforts.
</div>

::: {.column-margin}
<div class="h-yellow-box">
  Đưa ra kế hoạch tương lai của mình.
</div>

<div class="h-green-box">
  Khẳng định lại chương trình sẽ giúp mình thực hiện kế hoạch đó.
</div>
:::

*Ví dụ 2* ([nguồn](https://iastate.pressbooks.pub/statementofpurpose/chapter/section-6-annotated-sop-examples/))

<div class="example">
  Upon completing a doctoral degree in Counseling Psychology, [I intend to work as a professor]{.h-yellow} exploring the intersectionality between the Black experience, religion, and spirituality while also applying my findings through clinical supervision. Iowa State University’s Counseling Psychology Program will best [maximize my development in the field of psychology and prepare me to achieve my goals]{.h-green}. Ultimately, I want to be in a program where my identity is valued, and Iowa State University seems to fit just that.
</div>

::: {.column-margin}
<div class="h-yellow-box">
  Đưa ra kế hoạch tương lai của mình.
</div>

<div class="h-green-box">
  Khẳng định lại chương trình sẽ giúp mình thực hiện kế hoạch đó.
</div>
:::

## Những nội dung có thể đưa vào tùy trường hợp
*Phần này vẫn đang được cập nhật do tác giả chưa nghĩ ra nhiều thứ ...*

### Giải thích những điểm bất thường trong hồ sơ
::: {.callout-note title="Tóm lại là ..."}
Như cái tên gọi, giải thích về những điểm bất thường trong hồ sơ và **quá trình chúng ta khắc phục**, có thể là:

- Điểm thấp ở một số môn quan trọng
- Chuyển hướng trong sự nghiệp (trái ngành)
- Những khoảng thời gian không có hoạt động gì (gap year)

Thường được lồng ghép trong phần viết về các trải nghiệm và câu chuyện cá nhân.
:::

Chúng ta cùng xem một ví dụ cụ thể về giải thích cho GPA thấp (do [Grok](https://grok.com) bịa ra):

<div class="example">
  My journey into computer science began with excitement but also significant challenges. As a first-generation college student from a small town, transitioning to a demanding university environment overwhelmed me initially. [Balancing a part-time job to support my family with a rigorous coursework load led to lower grades in my freshman and sophomore years, particularly in foundational math and programming courses]{.h-red}. [Rather than letting this define me, I sought help: I joined study groups, met regularly with professors and advisors, and prioritized time management]{.h-yellow}. [By my junior year, these efforts paid off—I consistently earned A’s in advanced courses like algorithms and machine learning, raising my major GPA to 3.9 and graduating with strong recommendations from my capstone project advisor.]{.h-green}

  This experience taught me resilience and the value of seeking feedback—skills I’ve carried into my professional role, where I’ve successfully debugged complex systems under tight deadlines and mentored junior developers. Pursuing a Master’s at Carnegie Mellon, with its collaborative culture and world-class AI faculty, will allow me to build on this upward trajectory, deepening my expertise in machine learning while contributing persistence and real-world insights to the program.
</div>

::: {.column-margin}
<div class="h-red-box">
  Giải thích lý do bị điểm thấp
</div>

<div class="h-yellow-box">
  Cách khắc phục
</div>

<div class="h-green-box">
  Kết quả
</div>
:::

## Một số nội dung đặc thù cho học bổng

# Một số cấu trúc SOP cụ thể {#sec-sop-structure}
Sau đây là một cấu trúc SOP cụ thể. Hầu như các cấu trúc này chỉ khác nhau ở cách sắp xếp, triển khai ý, còn lại đều bao gồm các nội dung như trên. Do đó, phần này chỉ liệt kê các mục chính, còn nội dung cụ thể và cách viết các phần đã được trình bày ở trên.

## Cấu trúc cơ bản
Có thể xem chi tiết ở [đây](https://www.csulb.edu/sites/default/files/2023/documents/A%20Skeleton%20for%20Your%20Statement%20of%20Purpose%20Essay.pdf) hoặc [đây](https://graduate.northeastern.edu/knowledge-hub/how-to-write-a-statement-of-purpose/).


::: {.callout-note title="Cấu trúc cơ bản"}
1. Giới thiệu: Hook + đưa ra động lực nộp hồ sơ vào trường (thường gắn với mục tiêu luôn)
2. Trải nghiệm
    - Trải nghiệm 1
    - Trải nghiệm 2
    - ...
3. Sự phù hợp với chương trình
4. Kế hoạch tương lai
5. Kết bài: Khẳng định chương trình giúp mình đạt được mục tiêu, nếu được vào minhg sẽ đóng góp các thứ, ...
:::

Sau đây, chúng ta cùng xem một ví dụ về một bài viết theo cấu trúc này ([nguồn](https://www.uc.edu/news/articles/2024/11/personal-statement-examples-grad-school.html)). Người viết nộp hồ sơ vào chương trình Thạc sĩ ngành Y tế công cộng (Public Health). Trong nguồn này còn có nhiều bài khác cũng viết theo cấu trúc trên.

<div class="example">
  **[Giới thiệu]** My passion for public health was sparked during a volunteer trip to [country], where I worked alongside local health officials to improve sanitation and nutrition in rural communities. Witnessing firsthand the challenges that underserved populations face in accessing basic healthcare [motivated me to pursue a career in public health]{.h-yellow}. With a background in biology and a deep commitment to improving health equity, [I am eager to advance my education in public health at [university]]{.h-yellow} and [contribute to global efforts in disease prevention, health education and health policy reform]{.h-green}.

  **[Trải nghiệm 1: học hành]** I graduated with a Bachelor of Science in Biology from [undergraduate school], where I developed a strong foundation in the life sciences, including microbiology, epidemiology and biostatistics. During my coursework, [I became particularly interested in the social determinants of health]{.h-green}, which led me to take an independent study course in global health. My academic experience also included internships with local health organizations, where I assisted in health surveys and data collection efforts to identify risk factors in vulnerable populations.

  **[Trải nghiệm 2: đi làm]** After graduation, I joined [organization], a nonprofit dedicated to improving maternal health in underserved communities. As a program coordinator, [**[1]**]{.h-red} I worked on a project aimed at increasing awareness of prenatal care and reducing maternal mortality rates through educational workshops and access to healthcare resources. [**[2]**]{.h-red} My responsibilities included developing educational materials, conducting needs assessments, and evaluating program outcomes. [This experience highlighted the importance of health policy and community-based interventions, and reinforced my desire to pursue an MPH to develop more effective public health strategies.]{.h-green}

  **[Tại sao mình chọn chương trình này]** I am particularly drawn to the MPH program at [university] because of [**[1]**]{.h-green} its interdisciplinary approach to public health and its focus on global health, health policy and epidemiology. [**[2]**]{.h-green} I am excited about the opportunity to work with [faculty member] and other faculty members whose research on maternal and child health aligns with my interests. [**[3]**]{.h-green} The program’s emphasis on practical experience through field placements and internships is another reason why I believe it is the ideal fit for my career goals.

  **[Kế hoạch trong tương lai]** [My long-term goal]{.h-yellow} is to work with international health organizations to design and implement public health programs that reduce health disparities, particularly in low-income countries. I aim to specialize in global health policy, focusing on how policy reform can improve healthcare access and outcomes for marginalized communities. I believe [the MPH program at [university] will provide me with the knowledge and skills I need]{.h-green} to make a tangible impact on global public health.

  **[Kết bài]** The opportunity to study public health at [university] is one I approach with enthusiasm and dedication. I am eager to contribute to the program’s community of scholars and practitioners while gaining the expertise necessary to drive meaningful change in global health. I look forward to the opportunity to collaborate with faculty, peers and community partners to create lasting health improvements around the world.
</div>

::: {.column-margin}
<div class="h-yellow-box">
  Động lực chọn ngành + quyết định apply vào chương trình
</div>
<div class="h-green-box">
  Mục tiêu
</div>

<div class="h-green-box" style="margin-top: 8em;">
  **Why it matters**: Tác động của việc học đến sự phát triển của bản thân
</div>

<div class="h-red-box" style="margin-top: 8em;">
  **[1], [2]**: Mình đã làm gì
</div>

<div class="h-green-box">
  **Why it matters**: Tác động của công việc đến sự phát triển của bản thân
</div>

<div class="h-green-box" style="margin-top: 5em;">
  **[1], [2], [3]** là các lý do mình chọn chương trình này. Tuy nhiên trong thực tế đoạn này cần chi tiết hơn chứ ở đây mang tính chất minh họa là chính.
</div>

<div class="h-yellow-box" style="margin-top: 5em;">
  Mục tiêu sự nghiệp
</div>

<div class="h-green-box" style="margin-top: 2em;">
  Khẳng định lại chương trình sẽ giúp mình đạt mục tiêu
</div>
:::


## Cấu trúc thiên hướng kể chuyện
Trong cấu trúc này, chúng ta sẽ tập trung kể các trải nghiệm của mình thường là theo trình tự thời gian, sau đó kể đến thời điểm hiện tại mới đưa ra động lực và sự phù hợp với chương trình. Qua việc kể chuyện, chúng ta cũng kể ra sự phát triển trong nhận thức về mục tiêu của mình, từ đó dẫn đến động lực.

::: {.callout-note title="Cấu trúc thiên hướng kể chuyện"}
1. Hook + Trải nghiệm (thường là theo trình tự thời gian)
    - Trải nghiệm 1
    - Trải nghiệm 2
    - ...
2. Động lực nộp hồ sơ vào chương trình (thường gắn với mục tiêu luôn)
3. Sự phù hợp với chương trình
4. Kế hoạch tương lai
5. Kết bài 
:::

Chúng ta cùng xem ví dụ sau đây ([nguồn](https://www.collegeessayguy.com/blog/statement-of-purpose-examples)). Người viết nộp hồ sơ vào chương trình Thạc sĩ ngành Hải dương học (oceanography) trong vị trí trái ngành. Bài này chưa khẳng định rõ kế hoạch tương lai.

<div class="example">
  I was five years old, bundled in an oversized orange life jacket over the incredibly embarrassing sun-suit my mom insisted I wear. The translucent green water revealed a foreign, mystical world of vibrantly colored corals teaming with sea anemones and clownfish. I lay terrified on the oversized surfboard as my dad pushed me into a wave that was probably only a few inches tall but felt huge. I remember struggling to my feet, the colors of the reef zipping by as I sped through the water at what felt like a million miles per hour. [That moment changed the trajectory of my life.]{.h-grape} The ocean would forever become my muse. My parents are water people: my dad, an avid surfer; my mom, an avid swimmer. I soon followed suit. My love for surfing, swimming, and beach days quickly grew to dominate my life. 

  **[Tiếp tục kể theo trình thời gian]** Academically inclined and a straight-A student, I graduated college with honors. After two ill-fated medical school application cycles, however, I felt lost. Interviewing at different schools and meeting other applicants created a moment of clarity. While they wanted to discuss the pros and cons of different medical specialties, I wanted to look at weather models and swell charts. [For the first time in my life]{.h-red}, I turned away from academia and focused on other passions: travel, surfing, and exploring my place in the world. And, for the first time, doing so not through the lens of chasing academic success. [I also continued to build my math and science tutoring business]{.h-red}. I began tutoring in college as a way to make some money, but in the past few years of full-time tutoring, I’ve found that helping kids learn is rewarding in unexpected ways. I like helping kids become more excited about school and learning, seeing their “aha moments,” building bonds and helping mentor students, and feeling a sense of satisfaction upon seeing their (often unexpected) success. However, tutoring is very similar, year in and year out. For the most part, it’s the same curriculum – high school calculus and chemistry don’t really change that much. 

  **[Động lực + mục tiêu]** One passion that has stayed constant, and even intensified over the years, is my love for the ocean. I’ve taken every opportunity to travel, explore the coastline, and chase swells into remote corners of the world. [But, it has also become apparent in my travels how dramatically the ocean is changing]{.h-yellow}. My favorite island in Indonesia is being developed at light-speed. Each time I return, more and more of the coral is dead, replaced by villas for the world’s wealthy. The little beachside town in Mexico I went to with my family, formerly a turtle sanctuary, now houses luxury resorts and golf courses. And even at home in San Francisco, the parking lot where I spent countless hours hanging out with friends before and after surfing has been lost to erosion. Everywhere I look, the natural world is collapsing around us, and nowhere is this more evident than in my own safe haven: the ocean. My life is in a period of transition, just like the planet we call home. [As I’ve thought about what I want to accomplish with my career, I’ve realized that it’s my moral and ethical duty to protect the oceans, a place that has given me so much joy and shaped who I am]{.h-green}. I want formal training to gain the knowledge, skills, and credibility to join this fight.

  [**[1]**]{.h-red} I’ve spent hours and days teaching myself how to read nautical charts and weather forecasts. I’ve stared at the ocean, trying to hypothesize how the bathymetry of the ocean floor might mean that the waves break bigger on a west versus a southwest swell direction. I’ve poured over satellite images and radar projections of storm movement and considered how that impacts wind direction. I’ve become a decent, self taught hack, but I’ve never studied the ocean in a formal academic setting. Now, I want to. [**[2]**]{.h-green} The URI curriculum is the perfect fit to allow me to transition into a field about which I’m actually excited. Because I’ve never worked in the field, I appreciate that the curriculum is broad enough to allow exploration to determine my exact area of interest within oceanography. I’m excited about the opportunity for independent, experimental study to hone in on those areas. The online and self-paced nature of the program will allow me to continue working full time, pursue my recreational passion for the ocean, and start the process of pursuing a career for which I am passionate.
</div>

::: {.column-margin}
<div class="h-grape-box">
  Vừa là hook vừa nêu lên được người viết bắt đầu đam mê thế nào.
</div>

<div class="h-red-box" style="margin-top: 14em;">
  Người viết đã kể về một số việc họ làm. Qua đoạn số 2, chúng ta thấy được sự phát triển trong nhận thức của người viết: dù đã thử nhiều thứ nhưng vẫn chưa thấy thực sự đam mê.
</div>

<div class="h-yellow-box" style="margin-top: 19.5em;">
  Người viết bắt đầu kể về động lực
</div>

<div class="h-green-box" style="margin-top: 11.5em;">
  Mục tiêu
</div>

<div class="h-red-box" style="margin-top: 6em;">
  **[1]**: Các trải nghiệm học tập để chứng minh người viết đã chuẩn bị cho việc học cao học. Phần này khá cần thiết vì người viết trái ngành.
</div>

<div class="h-green-box">
  **[2]**: Sự phù hợp với chương trình
</div>
:::

## Cấu trúc "Structure is Magic"
Đây là một cấu trúc tương đối mới và hay, nhấn mạnh vào động lực và sự phù hợp của người viết thay vì các trải nghiệm. Sau đây là tóm tắt cấu trúc này. Rất khuyến khích mọi người đọc bản gốc ở [đây](https://writeivy.com/structure-is-magic-a-guide-to-the-graduate-sop/) để hiểu rõ triết lý đằng sau cấu trúc này.

::: {.callout-note title="Cấu trúc \"Structure is Magic\""}
1. Introductory Frame Narrative: Nói về lý do tại sao mình nộp hồ sơ, cụ thể hơn là mình gặp phải vấn đề gì và chương trình sẽ giúp mình giải quyết vấn đề đó và đạt được mục tiêu thế nào.
2. Why This Program: Tại sao mình lại chọn chương trình này?
3. Why You’re Qualified: Kể về các trải nghiệm của mình để thể hiện mình đã chuẩn bị tốt cho chương trình.
4. Closing Frame Narrative: Kết luận lại.
:::

Các bài mẫu có thể đọc ở [đây](https://writeivy.com/blog/). Một số ví dụ cụ thể:

- [MS Finance](https://writeivy.com/ms-finance-sop/)
- [Course-based MS AI](https://writeivy.com/course-based-masters-sop/)

# Phân tích một số bài mẫu